import tkinter as tk
from tkinter import ttk
import psutil
import threading
import time
import subprocess
import os
import sys
import json  
import keyboard  # Captures global hotkeys (Alt+T, Alt+Y)
from pystray import Icon, Menu, MenuItem  # System Tray management
from PIL import Image, ImageDraw  # Generates the tray icon dynamically

# --- PYINSTALLER SILENT STDOUT FIX ---
if sys.stdout is None: sys.stdout = open(os.devnull, 'w')
if sys.stderr is None: sys.stderr = open(os.devnull, 'w')

# --- SMART CONFIG PATH ENGINE ---
if getattr(sys, 'frozen', False):
    EXE_DIR = os.path.dirname(os.path.abspath(sys.executable))
else:
    EXE_DIR = os.path.dirname(os.path.abspath(__file__))

CONFIG_FILE = os.path.join(EXE_DIR, "config.json")

class ResourceMonitorApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Resource Manager")
        
        # --- HEADLESS PROFILE SIZE ---
        self.width = 240
        self.height = 126
        self.root.configure(bg="#0b0b0b")
        self.root.resizable(False, False)

        # --- THE FIX: FORCE WINDOWS UTILITY FRAME PROFILE ---
        # This completely strips the window context from ever populating a taskbar icon
        self.root.wm_attributes('-toolwindow', True)

        # Default Settings Variables
        self.is_visible = True
        self.current_position = "top-left"         
        self.current_alpha = 0.6                  

        # Load saved configurations 
        self.load_settings()

        # Fonts
        stat_font = ("Consolas", 10, "bold")

        # --- TELEMETRY READOUT PANELS ---
        self.cpu_label = tk.Label(root, text="CPU: LOADING...", font=stat_font, fg="#00ff00", bg="#0b0b0b")
        self.cpu_label.pack(anchor="w", padx=15, pady=(15, 2))

        self.gpu_label = tk.Label(root, text="GPU: LOADING...", font=stat_font, fg="#00ff00", bg="#0b0b0b")
        self.gpu_label.pack(anchor="w", padx=15, pady=2)

        self.ram_label = tk.Label(root, text="RAM: LOADING...", font=stat_font, fg="#00ff00", bg="#0b0b0b")
        self.ram_label.pack(anchor="w", padx=15, pady=2)

        self.proc_label = tk.Label(root, text="LMT: LOADING...", font=("Consolas", 9, "bold"), fg="#888888", bg="#0b0b0b")
        self.proc_label.pack(anchor="w", padx=15, pady=(4, 15))

        # Lifecycle Management Setup
        self.running = True
        
        # Telemetry Thread
        self.monitor_thread = threading.Thread(target=self.update_telemetry, daemon=True)
        self.monitor_thread.start()

        # --- GLOBAL HOTKEYS ---
        try:
            keyboard.add_hotkey('alt+t', self.toggle_overlay_visibility) 
            keyboard.add_hotkey('alt+y', self.open_settings_window)       
        except Exception:
            pass

        self.setup_system_tray()

        # --- ASYNCHRONOUS INITIALIZATION BUFFER ---
        self.root.after(100, self.initialize_overlay_styles)

    def initialize_overlay_styles(self):
        """Executes window overrides safely after the canvas has been generated by the OS"""
        try:
            self.root.overrideredirect(True)          # Strips borders safely
            self.root.attributes('-topmost', True)     # Pins overlay on top
            self.root.attributes('-alpha', self.current_alpha)  # Applies opacity
            self.apply_click_through()                # Activates click-through hooks
            self.reposition_window(self.current_position) # Snaps to preferred corner
            self.root.update()                        # Refresh window buffer
        except Exception:
            pass

    # --- WIN32 HARDWARE INPUT PASS-THROUGH ---
    def apply_click_through(self):
        try:
            import ctypes
            hwnd = int(self.root.frame(), 16)
            GWL_EXSTYLE = -20
            WS_EX_TRANSPARENT = 0x00000020
            WS_EX_LAYERED = 0x00080000

            user32 = ctypes.windll.user32
            styles = user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
            user32.SetWindowLongW(hwnd, GWL_EXSTYLE, styles | WS_EX_TRANSPARENT | WS_EX_LAYERED)
        except Exception:
            pass

    # --- SETTINGS CONFIGURATION (JSON) ---
    def load_settings(self):
        try:
            if os.path.exists(CONFIG_FILE):
                with open(CONFIG_FILE, "r") as f:
                    config = json.load(f)
                    self.current_position = config.get("position", "top-left")
                    self.current_alpha = config.get("transparency", 0.6)
        except Exception:
            pass 

    def save_settings(self):
        try:
            config_data = {
                "position": self.current_position,
                "transparency": self.current_alpha
            }
            with open(CONFIG_FILE, "w") as f:
                json.dump(config_data, f, indent=4)
        except Exception:
            pass

    # --- EDGE CORNER SNAPPING ENGINES ---
    def reposition_window(self, position):
        self.current_position = position
        screen_width = self.root.winfo_screenwidth()
        screen_height = self.root.winfo_screenheight() 

        if position == "top-left":
            x, y = 0, 0
        elif position == "top-right":
            x, y = screen_width - self.width, 0
        elif position == "bottom-left":
            x, y = 0, screen_height - self.height
        elif position == "bottom-right":
            x, y = screen_width - self.width, screen_height - self.height
        
        self.root.geometry(f"{self.width}x{self.height}+{x}+{y}")
        self.save_settings() 

    # --- DYNAMIC TRANSPARENCY UPDATER ---
    def update_transparency(self, value):
        self.current_alpha = float(value) / 100.0
        self.root.attributes('-alpha', self.current_alpha)
        if hasattr(self, 'transparency_val_label'):
            self.transparency_val_label.config(text=f"Opacity: {int(float(value))}%")
        self.save_settings()

    # --- ASYNCHRONOUS SETTINGS MODAL (Alt+Y) ---
    def open_settings_window(self):
        settings_win = tk.Toplevel(self.root)
        settings_win.title("Settings")
        settings_win.geometry("260x200") 
        settings_win.configure(bg="#151515")
        settings_win.resizable(False, False)
        settings_win.attributes('-topmost', True)

        label_font = ("Consolas", 10, "bold")

        pos_label = tk.Label(settings_win, text="Settings Overlay Position:", font=label_font, fg="#ffffff", bg="#151515")
        pos_label.pack(anchor="w", padx=15, pady=(15, 2))

        dropdown_var = tk.StringVar(value=self.current_position)
        def on_dropdown_select(event):
            self.reposition_window(dropdown_var.get())

        positions_list = ["top-left", "top-right", "bottom-left", "bottom-right"]
        dropdown = ttk.Combobox(settings_win, textvariable=dropdown_var, values=positions_list, state="readonly", width=22)
        dropdown.pack(anchor="w", padx=15, pady=5)
        dropdown.bind("<<ComboboxSelected>>", on_dropdown_select)

        current_percentage = int(self.current_alpha * 100)
        self.transparency_val_label = tk.Label(settings_win, text=f"Opacity: {current_percentage}%", font=label_font, fg="#ffffff", bg="#151515")
        self.transparency_val_label.pack(anchor="w", padx=15, pady=(15, 2))

        slider = tk.Scale(settings_win, from_=10, to=100, orient="horizontal", bg="#151515", fg="#ffffff",
                          troughcolor="#0b0b0b", highlightthickness=0, bd=0, showvalue=False,
                          command=self.update_transparency)
        slider.set(current_percentage) 
        slider.pack(anchor="w", fill="x", padx=15, pady=5)

    # --- ACCELERATOR SHORTCUT MANIPULATION (Alt+T) ---
    def toggle_overlay_visibility(self):
        if self.is_visible:
            self.is_visible = False
            self.root.withdraw()
        else:
            self.root.overrideredirect(True)
            self.is_visible = True
            self.root.deiconify()
            self.root.attributes('-topmost', True)
            self.root.attributes('-alpha', self.current_alpha)
            self.apply_click_through()  
            self.reposition_window(self.current_position)

    # --- BACKGROUND NOTIFICATION ICON ENGINE ---
    def generate_tray_icon(self):
        image = Image.new('RGB', (64, 64), color='#0b0b0b')
        dc = ImageDraw.Draw(image)
        dc.rectangle([(16, 16), (48, 48)], fill='#00ff00')
        return image

    def setup_system_tray(self):
        try:
            menu = Menu(
                MenuItem('Show HUD (Alt+T)', self.toggle_overlay_visibility, default=True),
                MenuItem('HUD Settings (Alt+Y)', self.open_settings_window),
                MenuItem('Exit Completely', self.on_close)
            )
            self.tray_icon = Icon("ResourceMonitor", self.generate_tray_icon(), "Resource Manager", menu)
            self.tray_thread = threading.Thread(target=self.tray_icon.run, daemon=True)
            self.tray_thread.start()
        except Exception:
            pass

    # --- HARDWARE SYSTEM ACCESS LAYER ---
    def get_gpu_data(self):
        try:
            cmd = ["nvidia-smi", "--query-gpu=utilization.gpu,temperature.gpu", "--format=csv,noheader,nounits"]
            result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, 
                                    text=True, creationflags=subprocess.CREATE_NO_WINDOW, timeout=0.4)
            if result.returncode == 0:
                data = result.stdout.strip().split(',')
                return f"GPU: {data[0].strip()}% | {data[1].strip()}°C"
        except Exception:
            pass
        return "GPU: Idle/Intg"

    def update_telemetry(self):
        while self.running:
            try:
                if self.is_visible:
                    cpu_usage = psutil.cpu_percent(interval=0.4)
                    gpu_text = self.get_gpu_data()
                    mem = psutil.virtual_memory()
                    ram_used = round(mem.used / (1024 ** 3), 1)

                    top_proc_name = "None"
                    top_proc_cpu = 0.0
                    for proc in psutil.process_iter(['name', 'cpu_percent']):
                        try:
                            if proc.info['cpu_percent'] > top_proc_cpu:
                                top_proc_cpu = proc.info['cpu_percent']
                                top_proc_name = proc.info['name']
                        except (psutil.NoSuchProcess, psutil.AccessDenied):
                            continue

                    if self.running and self.is_visible:
                        self.cpu_label.config(text=f"CPU: {int(cpu_usage)}%")
                        self.gpu_label.config(text=gpu_text)
                        self.ram_label.config(text=f"RAM: {int(mem.percent)}% ({ram_used}GB)")
                        
                        proc_short = top_proc_name[:12] + '..' if len(top_proc_name) > 12 else top_proc_name
                        self.proc_label.config(text=f"LMT: {proc_short} ({int(top_proc_cpu)}%)")

                time.sleep(1)
            except Exception:
                pass

    def on_close(self, icon=None, item=None):
        self.running = False
        try: keyboard.unhook_all()
        except Exception: pass
        if self.tray_icon:
            self.tray_icon.stop()
        self.root.after(0, self.root.destroy)

if __name__ == "__main__":
    window = tk.Tk()
    app = ResourceMonitorApp(window)
    window.mainloop()